require: rubocop-rails

Style/LambdaCall:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Layout/IndentFirstHashElement:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Layout/IndentFirstArgument:
  Enabled: false
Layout/AlignArguments:
  Enabled: false
Metrics/LineLength:
  Max: 120 # possibly change back to 80 before merge
AllCops:
  TargetRubyVersion: 2.6

# configuration explained
# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
